## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/

In [70]:
# import statements

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# check pytorch version via python syntax
print(torch.__version__)


1.13.1


## Introduction to Tensors

## Creating Tensors

In [99]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [100]:
scalar.ndim

0

In [101]:
# Get tensor back as Python int
scalar.item()

7

In [102]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [103]:
vector.ndim

1

In [104]:
vector.shape

torch.Size([2])

In [105]:
# MATRIX
# A matrix only has two dimensions; the row & column
matrix = torch.tensor([[7, 7, 3], [10, 5, 3]])
matrix

tensor([[ 7,  7,  3],
        [10,  5,  3]])

In [106]:
matrix.ndim

2

In [107]:
matrix[1]

tensor([10,  5,  3])

In [108]:
matrix.shape

torch.Size([2, 3])

In [109]:
# TENSOR
# A tensor has multiple dimensions
tensor = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
tensor # this goes beyond the row, column axis

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [110]:
tensor.ndim

3

In [111]:
tensor.shape

torch.Size([1, 3, 3])

In [112]:
# each dimension corresponds to the number of brackets
# the example below calls only one dimension which corresponds to the outer most bracket
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
# this example calls 2 dimensions
# first index has access to the first bracket (first dimension),
# and the second index has access to the second bracket which corresponds to the second dimension
tensor[0][0]

tensor([1, 2, 3])

In [114]:
tensor[0][1][1]

tensor(5)

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [115]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2331, 0.1573, 0.9897, 0.0627],
        [0.5042, 0.5597, 0.6055, 0.5980],
        [0.4464, 0.8331, 0.8707, 0.2343]])

In [116]:
r_shape = random_tensor.shape
r_shape # 3 rows, 4 columns

torch.Size([3, 4])

In [117]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # (height, width, color channels (R, G, B))
random_image_size_tensor.shape, random_image_size_tensor.ndim # 3 dimensions!

(torch.Size([224, 224, 3]), 3)

### Zero and Ones

In [118]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [119]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [120]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [121]:
# Use torch.range()
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
step_range = torch.arange(start=0, end=1000, step=77)
step_range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [123]:
# Creating tensors like
# generates a tensor that is "like" the input which basically has same shape
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

** Note:** Tensor datatypes is one of the 3 most frequent errors in PyTorch & Deep Learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [124]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [125]:
float_32_tensor.dtype

torch.float32

In [126]:
# can change the data type
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [127]:
# convert datatype
float_32_to_16 = float_32_tensor.type(torch.float16)
float_32_to_16

tensor([3., 6., 9.], dtype=torch.float16)