## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/

In [1]:
# import statements

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# check pytorch version via python syntax
print(torch.__version__)


1.13.1


## Introduction to Tensors

## Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
# A matrix only has two dimensions; the row & column
matrix = torch.tensor([[7, 7, 3], [10, 5, 3]])
matrix

tensor([[ 7,  7,  3],
        [10,  5,  3]])

In [9]:
matrix.ndim

2

In [10]:
matrix[1]

tensor([10,  5,  3])

In [11]:
matrix.shape

torch.Size([2, 3])

In [12]:
# TENSOR
# A tensor has multiple dimensions
tensor = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
tensor # this goes beyond the row, column axis

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
# each dimension corresponds to the number of brackets
# the example below calls only one dimension which corresponds to the outer most bracket
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
# this example calls 2 dimensions
# first index has access to the first bracket (first dimension),
# and the second index has access to the second bracket which corresponds to the second dimension
tensor[0][0]

tensor([1, 2, 3])

In [17]:
tensor[0][1][1]

tensor(5)

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7724, 0.5924, 0.9459, 0.5267],
        [0.5731, 0.8673, 0.3681, 0.0593],
        [0.3788, 0.5710, 0.9077, 0.6445]])

In [19]:
r_shape = random_tensor.shape
r_shape # 3 rows, 4 columns

torch.Size([3, 4])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # (height, width, color channels (R, G, B))
random_image_size_tensor.shape, random_image_size_tensor.ndim # 3 dimensions!

(torch.Size([224, 224, 3]), 3)

### Zero and Ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range()
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
step_range = torch.arange(start=0, end=1000, step=77)
step_range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
# Creating tensors like
# generates a tensor that is "like" the input which basically has same shape
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

** Note:** Tensor datatypes is one of the 3 most frequent errors in PyTorch & Deep Learning.
1. Tensors are not in the right datatype
2. Tensors are not in the right shape
3. Tensors are not on right device (cpu, gpu etc)

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
# can change the data type
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [30]:
# convert datatype
float_32_to_16 = float_32_tensor.type(torch.float16)
float_32_to_16

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
# multiplication of tensors with different shapes
# some operations will generate an error (not this one)
# but should be always aware of type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (not to create errors)

1. Check tensor data type - tensor.dtype
2. Check tensor shape - tensor.shape
3. Check tensor device - tensor.device

In [32]:
# first create tensor variable
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6787, 0.9344, 0.1175, 0.3294],
        [0.7809, 0.0809, 0.6458, 0.2735],
        [0.1463, 0.0303, 0.5251, 0.4166]])

In [33]:
# check details of "some_tensor"
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Tensor is on: {some_tensor.device}")

tensor([[0.6787, 0.9344, 0.1175, 0.3294],
        [0.7809, 0.0809, 0.6458, 0.2735],
        [0.1463, 0.0303, 0.5251, 0.4166]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [34]:
# create a tensor and add 10 to it
tensor_manip = torch.tensor([1, 2, 3])
print(tensor_manip)
print(f"tensor type is: {tensor_manip.dtype}") # check data type
print(tensor_manip + 10) # element addition
print(tensor_manip * 10) # element multiplication


# PyTorch in-built functions
print(torch.mul(tensor_manip, 20))
print(torch.add(tensor_manip, 1))


tensor([1, 2, 3])
tensor type is: torch.int64
tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([20, 40, 60])
tensor([2, 3, 4])


In [35]:
# Matrix Multiplication vs Element-wise Multiplication

# Element-wise Multiplication
tensor_ex1 = torch.tensor([1, 2, 3])
print("Element-wise Multiplication looks like:")
print(tensor_ex1, "*", tensor_ex1)
print(f"Equals: {tensor_ex1 * tensor_ex1}")


# Matrix Multiplication
tensor_matrix_mul = torch.matmul(tensor_ex1, tensor_ex1)
print("Matrix Multiplication result is:")
print(tensor_matrix_mul)

# although they are both row matrices, the matmul function reads it as column matrix


Element-wise Multiplication looks like:
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Matrix Multiplication result is:
tensor(14)


In [36]:
%%time

# the time function has to be at the top of the block
# the function operates for the entire block, so it doesn't work if it's located in the middle

value = 0
for i in range(len(tensor_ex1)):
    value += tensor_ex1[i] * tensor_ex1[i]
print(value)

tensor(14)
CPU times: user 1.24 ms, sys: 980 µs, total: 2.22 ms
Wall time: 2.89 ms


In [37]:
%%time
torch.matmul(tensor_ex1, tensor_ex1)

CPU times: user 34 µs, sys: 5 µs, total: 39 µs
Wall time: 42 µs


tensor(14)

### Satisfying Matrix Multiplication

There are two conditions for a successful matrix multiplication:
1. The **inner dimensions** must match:
* `@` is equivalent to `torch.matmul`
* `(3, 2) @ (3, 2)` doesn't work
* `(2, 3) @ (3, 2)` does work

2. The resulting matrix has the shape of the **outer dimensions:**
* `(2, 3) @ (3, 2)` -> `(2, 2)`

In [38]:
# this generates an shape mismatch error
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

# this works
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.9187, 0.2950],
        [0.5248, 0.1532]])

In [39]:
torch.matmul(torch.rand(10, 3), torch.rand(3, 5)).shape

torch.Size([10, 5])

### Basic Numerical Operations - sum, min, max, arg, mean

In [40]:
# Find the mean - note: torch.mean() function requires a tensor of float
x = torch.arange(0, 100, 10)
print(x, x.dtype)
print(x.argmin()) # this is the index value
print(x[0]) # this is the actual numerical value
print(x.argmax())
print(x[x.argmax()])

# make sure to change data type so it is compatible
# the mean function only operates on floating points or complext dtypes
# x.dtype is int64 before we convert it to float32
mean1, mean2 = torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
print(mean1, mean2)
print(x.sum(), torch.sum(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.int64
tensor(0)
tensor(0)
tensor(9)
tensor(90)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


### Reshaping, Stacking, Squeezing and Unsqueezing Tensors

##### Manipulate Tensors to shape them in some certain way

* Reshaping - reshapes an input tensor to defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [41]:
# tensor shape issues!

# create tensor
# re-importing allows us to use torch from this cell (not run the cells above)
import torch
x = torch.arange(1.0, 10.0)
x, x.shape, x.dtype, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.float32,
 1)

In [42]:
# Add an extra dimension
# reshaping needs to be compatible with the original tensor we are reshaping

x_reshaped_1 = x.reshape(1, 9) # row=1, col=9
print(x_reshaped_1, x_reshaped_1.shape, x_reshaped_1.ndim)

x_reshaped_2 = x.reshape(9, 1) # row=9, col=1
print(x_reshaped_2, x_reshaped_2.shape, x_reshaped_2.ndim)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9]) 2
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1]) 2


In [43]:
x_1 = torch.arange(1.0, 11.0)
x_reshaped_3 = x_1.reshape(5, 2) # row=5, col=2
print(x_reshaped_3, x_reshaped_3.shape, x_reshaped_3.ndim)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.Size([5, 2]) 2


In [44]:
# Change the view
x = torch.arange(1.0, 10.0)
print(f"This is Original: {x}")

# we are changin the view to (1, 9)
# so viewing through 'z' will be a 2 dimensional tensor
z = x.view(1, 9)
y = x.view(9) # now 'y' also shares the same memory address
print(f"This is y (no change in dimension: {y}")
print(f"This is the view through 'z': {z, z.shape}")

# "view" enables z to share the same memory location as x
# changing z changes x because view of a tensor shares the same memory as the original variable
# the view of z will stay the same, but the value in the memory will change for all the variables that share the same memory address

z[:, 0] = 5 # change first element of z to 5
print(f"Both z and x values change: {z, x}") # will also change x since they share the same memory location, but different dimension
print(f"Final z: {z}")
print(f"Final x: {x}")
print(f"Final y: {y}")

This is Original: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
This is y (no change in dimension: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
This is the view through 'z': (tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))
Both z and x values change: (tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))
Final z: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Final x: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Final y: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [45]:
# Stack tensors on top of each other - concatenation
x_stacked_ver = torch.stack([x, x, x, x], dim=0) # dimension of stacking (row, col = 0, 1)
x_stacked_hor = torch.stack([x, x, x, x], dim=1) # re-arranges for horizontal stacking
print(x_stacked_ver)
print(x_stacked_hor)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [46]:
# torch.squeeze() - remove all single dimensions from a target tensor
# z = reshaped version of x
print(z)
print(z.shape)
print(z.squeeze()) # doesn't modify the original z
print(z.squeeze().shape) # reduced dimension

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


In [47]:
# torch.unsqueeze() - adds single dimension to a target tensor at a specific dim
z_squeezed = z.squeeze()
print(f"Previous target: {z_squeezed}")
print(f"Previous shape: {z_squeezed.shape}")

# Add an extra dimension with unsqueeze
z_unsqueezed_0 = z_squeezed.unsqueeze(dim=0)
z_unsqueezed_1 = z_squeezed.unsqueeze(dim=1)
print(f"New tensor: {z_unsqueezed_0}")
print(f"New shape: {z_unsqueezed_0.shape}")
# print(f"New tensor: {z_unsqueezed_1}")
# print(f"New shape: {z_unsqueezed_1.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [48]:
# torch.permute - rearragnes the dimensions of a target tensor in a specified order
# useful to apply to images in which there are 3 dimensions (width, height, color channels)
# important part deep learning is to turn the data into numerical representation

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the dim order
# uses indices when rearranging
x_permuted = x_original.permute(2, 0, 1)

print(f"Original Shape: {x_original.shape}")
print(f"Permutated Shape: {x_permuted.shape}")

Original Shape: torch.Size([224, 224, 3])
Permutated Shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [51]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3) # 3 dimensional
print(x, x.shape)

# index on the first dimension (dim=0)
print(x[0])

# index on the middle bracket (dim=1)
print(x[0][0])

# index on most inner bracket (dim=2)
print(x[0][0][0])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


### PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, wnat in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [56]:
# NumPy Array to Tensor

array = np.arange(1.0, 8.0) # dtype = float64
tensor = torch.from_numpy(array) # dtype = float64
print(array, tensor)

# be aware of dtype
# numpy default data type = float64
# pytorch default data type = float32

# change dtype
tensor = torch.from_numpy(array).type(torch.float32)
print(tensor, tensor.dtype)
print()

# change value of array. does it affect tensor?
tensor = torch.from_numpy(array)
array = array + 1 # add scalar value to each element
print(array, tensor)


[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
tensor([1., 2., 3., 4., 5., 6., 7.]) torch.float32

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [58]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor, tensor.dtype)
print(numpy_tensor, numpy_tensor.dtype) # reflects original data type of torch

tensor([1., 1., 1., 1., 1., 1., 1.]) torch.float32
[1. 1. 1. 1. 1. 1. 1.] float32
