## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/

In [1]:
# import statements

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# check pytorch version via python syntax
print(torch.__version__)


1.13.1


## Introduction to Tensors

## Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
# A matrix only has two dimensions; the row & column
matrix = torch.tensor([[7, 7, 3], [10, 5, 3]])
matrix

tensor([[ 7,  7,  3],
        [10,  5,  3]])

In [9]:
matrix.ndim

2

In [10]:
matrix[1]

tensor([10,  5,  3])

In [11]:
matrix.shape

torch.Size([2, 3])

In [12]:
# TENSOR
# A tensor has multiple dimensions
tensor = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
tensor # this goes beyond the row, column axis

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
# each dimension corresponds to the number of brackets
# the example below calls only one dimension which corresponds to the outer most bracket
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
# this example calls 2 dimensions
# first index has access to the first bracket (first dimension),
# and the second index has access to the second bracket which corresponds to the second dimension
tensor[0][0]

tensor([1, 2, 3])

In [17]:
tensor[0][1][1]

tensor(5)

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8051, 0.6477, 0.1224, 0.3481],
        [0.6333, 0.9717, 0.0343, 0.0770],
        [0.0169, 0.3127, 0.2564, 0.7879]])

In [19]:
r_shape = random_tensor.shape
r_shape # 3 rows, 4 columns

torch.Size([3, 4])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # (height, width, color channels (R, G, B))
random_image_size_tensor.shape, random_image_size_tensor.ndim # 3 dimensions!

(torch.Size([224, 224, 3]), 3)

### Zero and Ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range()
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
step_range = torch.arange(start=0, end=1000, step=77)
step_range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
# Creating tensors like
# generates a tensor that is "like" the input which basically has same shape
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

** Note:** Tensor datatypes is one of the 3 most frequent errors in PyTorch & Deep Learning.
1. Tensors are not in the right datatype
2. Tensors are not in the right shape
3. Tensors are not on right device (cpu, gpu etc)

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
# can change the data type
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [30]:
# convert datatype
float_32_to_16 = float_32_tensor.type(torch.float16)
float_32_to_16

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
# multiplication of tensors with different shapes
# some operations will generate an error (not this one)
# but should be always aware of type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (not to create errors)

1. Check tensor data type - tensor.dtype
2. Check tensor shape - tensor.shape
3. Check tensor device - tensor.device

In [35]:
# first create tensor variable
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7915, 0.7592, 0.5410, 0.3231],
        [0.0983, 0.0790, 0.8772, 0.0524],
        [0.0649, 0.5605, 0.9152, 0.7314]])

In [36]:
# check details of "some_tensor"
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Tensor is on: {some_tensor.device}")

tensor([[0.7915, 0.7592, 0.5410, 0.3231],
        [0.0983, 0.0790, 0.8772, 0.0524],
        [0.0649, 0.5605, 0.9152, 0.7314]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [38]:
# create a tensor and add 10 to it
tensor_manip = torch.tensor([1, 2, 3])
print(tensor_manip)
print(f"tensor type is: {tensor_manip.dtype}") # check data type
print(tensor_manip + 10) # element addition
print(tensor_manip * 10) # element multiplication


# PyTorch in-built functions
print(torch.mul(tensor_manip, 20))
print(torch.add(tensor_manip, 1))


tensor([1, 2, 3])
tensor type is: torch.int64
tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([20, 40, 60])
tensor([2, 3, 4])


In [41]:
# Matrix Multiplication vs Element-wise Multiplication

# Element-wise Multiplication
tensor_ex1 = torch.tensor([1, 2, 3])
print("Element-wise Multiplication looks like:")
print(tensor_ex1, "*", tensor_ex1)
print(f"Equals: {tensor_ex1 * tensor_ex1}")


# Matrix Multiplication
tensor_matrix_mul = torch.matmul(tensor_ex1, tensor_ex1)
print("Matrix Multiplication result is:")
print(tensor_matrix_mul)

# although they are both row matrices, the matmul function reads it as column matrix


Element-wise Multiplication looks like:
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Matrix Multiplication result is:
tensor(14)


In [56]:
%%time

# the time function has to be at the top of the block
# the function operates for the entire block, so it doesn't work if it's located in the middle

value = 0
for i in range(len(tensor_ex1)):
    value += tensor_ex1[i] * tensor_ex1[i]
print(value)

tensor(14)
CPU times: user 1.52 ms, sys: 1.26 ms, total: 2.77 ms
Wall time: 3.47 ms


In [57]:
%%time
torch.matmul(tensor_ex1, tensor_ex1)

CPU times: user 252 µs, sys: 76 µs, total: 328 µs
Wall time: 324 µs


tensor(14)