## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/

In [ ]:
# import statements

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# check pytorch version via python syntax
print(torch.__version__)


1.13.1


## Introduction to Tensors

## Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
matrix = torch.tensor([[7, 7, 3], [10, 5, 3]])
matrix

tensor([[ 7,  7,  3],
        [10,  5,  3]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([10,  5,  3])

In [ ]:
matrix.shape

torch.Size([2, 3])

In [ ]:
# TENSOR
tensor = torch.tensor([[[[1, 2, 3],[4, 5, 6],[7, 8, 9]]]])